"use client"

import { useEffect, useState, useCallback } from "react"
import { useRouter } from "next/navigation"
import { Bell, Sparkles } from "@/components/icons"
import {
  DropdownMenu, DropdownMenuContent, DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { cn } from "@/lib/utils"

interface CoachNotification {
  id: string
  kind: string
  title: string
  body: string
  conversation_id: string | null
  read_at: string | null
  created_at: string
}

// Poll while the app is open so a reminder generated by the cron shows up
// without a refresh. The user asked for in-app delivery now; native push is a
// future layer over the same coach_notifications rows.
const POLL_MS = 60_000

function timeAgo(iso: string): string {
  try {
    const diff = Date.now() - new Date(iso).getTime()
    const min = Math.round(diff / 60000)
    if (min < 1) return "agora"
    if (min < 60) return `${min} min`
    const h = Math.round(min / 60)
    if (h < 24) return `${h} h`
    return `${Math.round(h / 24)} d`
  } catch {
    return ""
  }
}

export function NotificationBell() {
  const router = useRouter()
  const [items, setItems] = useState<CoachNotification[]>([])
  const [unread, setUnread] = useState(0)
  const [open, setOpen] = useState(false)

  const load = useCallback(async () => {
    try {
      const res = await fetch("/api/coach/notifications", { cache: "no-store" })
      if (!res.ok) return
      const payload = await res.json().catch(() => ({}))
      setItems((payload.notifications ?? []) as CoachNotification[])
      setUnread(typeof payload.unread === "number" ? payload.unread : 0)
    } catch {
      // silent — the bell is non-critical
    }
  }, [])

  useEffect(() => {
    void load()
    const id = setInterval(load, POLL_MS)
    return () => clearInterval(id)
  }, [load])

  const markAllRead = useCallback(async () => {
    if (unread === 0) return
    setUnread(0)
    setItems((prev) => prev.map((n) => ({ ...n, read_at: n.read_at ?? new Date().toISOString() })))
    try {
      await fetch("/api/coach/notifications", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ all: true }),
      })
    } catch {
      // ignore — next poll reconciles
    }
  }, [unread])

  const onOpenChange = useCallback((next: boolean) => {
    setOpen(next)
    if (next) void markAllRead()
  }, [markAllRead])

  const openNotification = useCallback((n: CoachNotification) => {
    setOpen(false)
    router.push(n.conversation_id ? `/coach?c=${n.conversation_id}` : "/coach")
  }, [router])

  return (
    <DropdownMenu open={open} onOpenChange={onOpenChange}>
      <DropdownMenuTrigger asChild>
        <button
          className="relative w-8 h-8 flex items-center justify-center rounded-xl text-[#1a3a2a]/60 hover:text-[#1a3a2a] hover:bg-[#1a3a2a]/5 transition-all"
          aria-label={unread > 0 ? `${unread} lembretes não lidos` : "Lembretes"}
        >
          <Bell className="h-4 w-4" />
          {unread > 0 && (
            <span className="absolute -top-0.5 -right-0.5 min-w-[16px] h-4 px-1 rounded-full bg-[#c4614a] text-white text-[10px] font-bold flex items-center justify-center">
              {unread > 9 ? "9+" : unread}
            </span>
          )}
        </button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-[320px] p-0 bg-[#faf8f4] border-[#e4ddd4]">
        <div className="px-4 py-3 border-b border-[#e4ddd4]">
          <p className="text-sm font-bold text-[#1a3a2a]">Lembretes do coach</p>
        </div>
        <div className="max-h-[60vh] overflow-y-auto">
          {items.length === 0 ? (
            <p className="text-sm text-[#1a3a2a]/50 font-body text-center py-10 px-4">
              Sem lembretes por enquanto. Seu coach te avisa nas horas das refeições.
            </p>
          ) : (
            items.map((n) => (
              <button
                key={n.id}
                onClick={() => openNotification(n)}
                className={cn(
                  "w-full text-left px-4 py-3 flex gap-3 border-b border-[#e4ddd4]/60 last:border-0 hover:bg-[#1a3a2a]/[0.03] transition-colors",
                  !n.read_at && "bg-[#1a3a2a]/[0.04]",
                )}
              >
                <div className="w-8 h-8 rounded-full bg-[#1a3a2a]/10 flex items-center justify-center shrink-0">
                  <Sparkles className="w-4 h-4 text-[#1a3a2a]" />
                </div>
                <div className="min-w-0 flex-1">
                  <div className="flex items-center justify-between gap-2">
                    <p className="text-sm font-semibold text-[#1a3a2a] truncate">{n.title}</p>
                    <span className="text-[10px] text-[#1a3a2a]/40 shrink-0">{timeAgo(n.created_at)}</span>
                  </div>
                  <p className="text-xs text-[#1a3a2a]/60 font-body leading-snug line-clamp-2 mt-0.5">{n.body}</p>
                </div>
              </button>
            ))
          )}
        </div>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
