import { NextResponse } from 'next/server'

export async function POST() {
  try {
    // TODO: Replace with actual Claude API integration
    // For now, return hardcoded mock data

    const mockMealPlan = {
      weekStartDate: '2025-01-13',
      meals: {
        monday: {
          breakfast: {
            name: 'Greek Yogurt Parfait with Berries',
            description: 'Creamy Greek yogurt layered with mixed berries, chia seeds, and a drizzle of honey',
            calories: 320,
            protein_g: 18,
            carbs_g: 42,
            fat_g: 8,
          },
          snack1: {
            name: 'Apple Slices with Almond Butter',
            description: 'Crisp apple slices paired with natural almond butter',
            calories: 180,
            protein_g: 4,
            carbs_g: 22,
            fat_g: 9,
          },
          lunch: {
            name: 'Grilled Chicken Quinoa Bowl',
            description: 'Herb-marinated grilled chicken over quinoa with roasted vegetables and tahini dressing',
            calories: 480,
            protein_g: 38,
            carbs_g: 45,
            fat_g: 14,
          },
          snack2: {
            name: 'Hummus with Carrot Sticks',
            description: 'Homemade hummus with fresh carrot and cucumber sticks',
            calories: 150,
            protein_g: 5,
            carbs_g: 18,
            fat_g: 7,
          },
          dinner: {
            name: 'Baked Salmon with Sweet Potato',
            description: 'Herb-crusted salmon fillet with roasted sweet potato and steamed broccoli',
            calories: 520,
            protein_g: 42,
            carbs_g: 38,
            fat_g: 18,
          },
        },
        tuesday: {
          breakfast: {
            name: 'Overnight Oats with Banana',
            description: 'Steel-cut oats soaked overnight with banana, cinnamon, and walnuts',
            calories: 340,
            protein_g: 12,
            carbs_g: 52,
            fat_g: 10,
          },
          snack1: {
            name: 'Mixed Nuts and Dried Fruit',
            description: 'Trail mix with almonds, cashews, and unsweetened dried cranberries',
            calories: 200,
            protein_g: 6,
            carbs_g: 18,
            fat_g: 13,
          },
          lunch: {
            name: 'Mediterranean Chickpea Salad',
            description: 'Chickpeas, cucumber, tomatoes, red onion, feta, and olive oil dressing',
            calories: 420,
            protein_g: 16,
            carbs_g: 48,
            fat_g: 18,
          },
          snack2: {
            name: 'Celery with Peanut Butter',
            description: 'Celery sticks filled with natural peanut butter',
            calories: 160,
            protein_g: 7,
            carbs_g: 10,
            fat_g: 12,
          },
          dinner: {
            name: 'Turkey Meatballs with Zucchini Noodles',
            description: 'Lean turkey meatballs over zucchini noodles with marinara sauce',
            calories: 460,
            protein_g: 36,
            carbs_g: 32,
            fat_g: 18,
          },
        },
        wednesday: {
          breakfast: {
            name: 'Veggie Scramble with Avocado',
            description: 'Eggs scrambled with spinach, tomatoes, and mushrooms, topped with avocado',
            calories: 360,
            protein_g: 22,
            carbs_g: 18,
            fat_g: 22,
          },
          snack1: {
            name: 'Cottage Cheese with Berries',
            description: 'Low-fat cottage cheese with fresh blueberries and strawberries',
            calories: 170,
            protein_g: 15,
            carbs_g: 20,
            fat_g: 3,
          },
          lunch: {
            name: 'Lentil Soup with Whole Grain Bread',
            description: 'Hearty lentil soup with vegetables and a slice of whole grain bread',
            calories: 440,
            protein_g: 22,
            carbs_g: 68,
            fat_g: 8,
          },
          snack2: {
            name: 'Greek Yogurt with Granola',
            description: 'Plain Greek yogurt with homemade granola',
            calories: 210,
            protein_g: 12,
            carbs_g: 28,
            fat_g: 6,
          },
          dinner: {
            name: 'Grilled Shrimp Tacos',
            description: 'Grilled shrimp in corn tortillas with cabbage slaw and lime crema',
            calories: 480,
            protein_g: 32,
            carbs_g: 52,
            fat_g: 14,
          },
        },
        thursday: {
          breakfast: {
            name: 'Smoothie Bowl with Toppings',
            description: 'Berry smoothie bowl topped with granola, coconut flakes, and fresh fruit',
            calories: 380,
            protein_g: 14,
            carbs_g: 58,
            fat_g: 12,
          },
          snack1: {
            name: 'Hard-Boiled Eggs with Cherry Tomatoes',
            description: 'Two hard-boiled eggs with a handful of cherry tomatoes',
            calories: 180,
            protein_g: 14,
            carbs_g: 6,
            fat_g: 11,
          },
          lunch: {
            name: 'Asian-Style Tofu Stir-Fry',
            description: 'Crispy tofu with mixed vegetables in a ginger-garlic sauce over brown rice',
            calories: 460,
            protein_g: 20,
            carbs_g: 58,
            fat_g: 16,
          },
          snack2: {
            name: 'Edamame with Sea Salt',
            description: 'Steamed edamame lightly salted',
            calories: 150,
            protein_g: 12,
            carbs_g: 12,
            fat_g: 6,
          },
          dinner: {
            name: 'Chicken Fajita Bowl',
            description: 'Grilled chicken with peppers and onions over cilantro-lime rice',
            calories: 500,
            protein_g: 40,
            carbs_g: 48,
            fat_g: 14,
          },
        },
        friday: {
          breakfast: {
            name: 'Whole Grain Toast with Avocado',
            description: 'Multigrain toast topped with mashed avocado, hemp seeds, and cherry tomatoes',
            calories: 340,
            protein_g: 12,
            carbs_g: 38,
            fat_g: 16,
          },
          snack1: {
            name: 'Protein Smoothie',
            description: 'Banana, spinach, protein powder, and almond milk smoothie',
            calories: 220,
            protein_g: 20,
            carbs_g: 28,
            fat_g: 4,
          },
          lunch: {
            name: 'Tuna Salad Lettuce Wraps',
            description: 'Tuna salad made with Greek yogurt wrapped in butter lettuce leaves',
            calories: 380,
            protein_g: 34,
            carbs_g: 18,
            fat_g: 18,
          },
          snack2: {
            name: 'Bell Pepper Strips with Guacamole',
            description: 'Fresh bell pepper strips with homemade guacamole',
            calories: 140,
            protein_g: 3,
            carbs_g: 14,
            fat_g: 10,
          },
          dinner: {
            name: 'Baked Cod with Asparagus',
            description: 'Lemon-herb baked cod with roasted asparagus and wild rice',
            calories: 460,
            protein_g: 38,
            carbs_g: 42,
            fat_g: 12,
          },
        },
        saturday: {
          breakfast: {
            name: 'Protein Pancakes with Berries',
            description: 'Whole wheat protein pancakes topped with fresh berries and maple syrup',
            calories: 400,
            protein_g: 24,
            carbs_g: 54,
            fat_g: 10,
          },
          snack1: {
            name: 'Rice Cakes with Almond Butter',
            description: 'Brown rice cakes spread with almond butter and sliced banana',
            calories: 190,
            protein_g: 5,
            carbs_g: 26,
            fat_g: 8,
          },
          lunch: {
            name: 'Black Bean Burrito Bowl',
            description: 'Black beans, brown rice, salsa, cheese, and guacamole',
            calories: 520,
            protein_g: 22,
            carbs_g: 72,
            fat_g: 16,
          },
          snack2: {
            name: 'Watermelon with Feta',
            description: 'Fresh watermelon cubes with crumbled feta and mint',
            calories: 130,
            protein_g: 4,
            carbs_g: 18,
            fat_g: 5,
          },
          dinner: {
            name: 'Grass-Fed Beef with Roasted Vegetables',
            description: 'Lean beef medallions with roasted root vegetables and quinoa',
            calories: 540,
            protein_g: 42,
            carbs_g: 44,
            fat_g: 20,
          },
        },
        sunday: {
          breakfast: {
            name: 'Veggie Omelet with Whole Grain Toast',
            description: 'Three-egg omelet with vegetables and a slice of whole grain toast',
            calories: 380,
            protein_g: 26,
            carbs_g: 28,
            fat_g: 18,
          },
          snack1: {
            name: 'Kale Chips',
            description: 'Baked kale chips seasoned with nutritional yeast',
            calories: 100,
            protein_g: 4,
            carbs_g: 12,
            fat_g: 4,
          },
          lunch: {
            name: 'Chicken Caesar Salad',
            description: 'Grilled chicken over romaine with homemade Caesar dressing and parmesan',
            calories: 440,
            protein_g: 38,
            carbs_g: 24,
            fat_g: 22,
          },
          snack2: {
            name: 'Dark Chocolate with Almonds',
            description: '70% dark chocolate squares with a handful of almonds',
            calories: 180,
            protein_g: 5,
            carbs_g: 16,
            fat_g: 13,
          },
          dinner: {
            name: 'Vegetable Curry with Chickpeas',
            description: 'Mixed vegetable and chickpea curry over basmati rice',
            calories: 500,
            protein_g: 18,
            carbs_g: 78,
            fat_g: 14,
          },
        },
      },
      groceryList: [
        { name: 'Salmon Fillets', quantity: '4 x 170g', category: 'protein', estimatedPrice: 18.99 },
        { name: 'Chicken Breast', quantity: '1.5 kg', category: 'protein', estimatedPrice: 14.99 },
        { name: 'Ground Turkey', quantity: '500g', category: 'protein', estimatedPrice: 8.99 },
        { name: 'Shrimp', quantity: '400g', category: 'protein', estimatedPrice: 12.99 },
        { name: 'Cod Fillets', quantity: '2 x 200g', category: 'protein', estimatedPrice: 10.99 },
        { name: 'Grass-Fed Beef Medallions', quantity: '4 x 150g', category: 'protein', estimatedPrice: 16.99 },
        { name: 'Firm Tofu', quantity: '1 block (400g)', category: 'protein', estimatedPrice: 3.49 },
        { name: 'Greek Yogurt', quantity: '1kg tub', category: 'dairy', estimatedPrice: 5.99 },
        { name: 'Cottage Cheese', quantity: '500g', category: 'dairy', estimatedPrice: 4.49 },
        { name: 'Eggs', quantity: '18 count', category: 'dairy', estimatedPrice: 6.99 },
        { name: 'Feta Cheese', quantity: '200g', category: 'dairy', estimatedPrice: 5.49 },
        { name: 'Quinoa', quantity: '500g bag', category: 'pantry', estimatedPrice: 4.99 },
        { name: 'Brown Rice', quantity: '1kg bag', category: 'pantry', estimatedPrice: 3.99 },
        { name: 'Lentils', quantity: '500g bag', category: 'pantry', estimatedPrice: 2.99 },
        { name: 'Chickpeas', quantity: '2 cans', category: 'pantry', estimatedPrice: 3.98 },
        { name: 'Black Beans', quantity: '2 cans', category: 'pantry', estimatedPrice: 3.98 },
        { name: 'Steel-Cut Oats', quantity: '500g', category: 'pantry', estimatedPrice: 4.49 },
        { name: 'Almond Butter', quantity: '350g jar', category: 'pantry', estimatedPrice: 8.99 },
        { name: 'Mixed Berries', quantity: '2 cups frozen', category: 'produce', estimatedPrice: 6.99 },
        { name: 'Bananas', quantity: '6 count', category: 'produce', estimatedPrice: 2.49 },
        { name: 'Apples', quantity: '4 count', category: 'produce', estimatedPrice: 3.99 },
        { name: 'Avocados', quantity: '6 count', category: 'produce', estimatedPrice: 8.99 },
        { name: 'Sweet Potatoes', quantity: '4 medium', category: 'produce', estimatedPrice: 4.99 },
        { name: 'Spinach', quantity: '2 bunches', category: 'produce', estimatedPrice: 5.98 },
        { name: 'Broccoli', quantity: '2 heads', category: 'produce', estimatedPrice: 4.98 },
        { name: 'Asparagus', quantity: '1 bunch', category: 'produce', estimatedPrice: 4.99 },
        { name: 'Bell Peppers', quantity: '4 mixed colors', category: 'produce', estimatedPrice: 6.99 },
        { name: 'Zucchini', quantity: '3 medium', category: 'produce', estimatedPrice: 3.99 },
        { name: 'Cherry Tomatoes', quantity: '2 pints', category: 'produce', estimatedPrice: 5.98 },
        { name: 'Romaine Lettuce', quantity: '2 heads', category: 'produce', estimatedPrice: 4.98 },
      ],
    }

    return NextResponse.json(mockMealPlan)
  } catch (error) {
    console.error('Meal plan generation error:', error)
    return NextResponse.json(
      { error: 'Failed to generate meal plan' },
      { status: 500 }
    )
  }
}
